In [ ]:
#Universal Function
- it is used to perform element-wise operation on data of array.

In [80]:
import numpy as np
arr=np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#square root
print('square root: ',np.sqrt(arr))

square root:  [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [10]:
#exponential
print('exponential: ',np.exp(arr))

exponential:  [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [22]:
a=np.random.rand(20)
print(a)

[0.46765149 0.40713892 0.62137272 0.28218308 0.22034327 0.69665363
 0.03047482 0.55866645 0.07287329 0.71186699 0.5574209  0.38877855
 0.96585272 0.73292132 0.47775278 0.94716453 0.01125616 0.6673592
 0.32746627 0.56109333]


In [46]:
b=np.random.randint(1,7)
print(b)

6


In [56]:
c=np.random.randint(0,50,5)
print(c)

[31 25 45 27 44]


In [68]:
a=np.random.rand(10)
b=np.random.rand(10)
print (a)
print(b)

[0.87205121 0.79226398 0.94692437 0.80773721 0.55184586 0.96027432
 0.78494359 0.88070867 0.12237028 0.57588545]
[0.16355316 0.58278124 0.48393445 0.79503673 0.41937298 0.507573
 0.19206201 0.85089142 0.12983782 0.89088049]


In [70]:
print('Minimum: ',np.minimum(a,b))
print('Maximum: ',np.maximum(a,b))

Minimum:  [0.16355316 0.58278124 0.48393445 0.79503673 0.41937298 0.507573
 0.19206201 0.85089142 0.12237028 0.57588545]
Maximum:  [0.87205121 0.79226398 0.94692437 0.80773721 0.55184586 0.96027432
 0.78494359 0.88070867 0.12983782 0.89088049]


In [72]:
np.min(a)

0.12237028420002449

In [74]:
np.max(a)

0.9602743224505961

In [82]:
np.min(arr)
np.max(arr)

9

In [88]:
print(arr)
np.min(arr,axis=0)

[0 1 2 3 4 5 6 7 8 9]


0

In [102]:
num=np.random.randint(1,20,10)
num

array([11, 16,  7,  8,  5,  9, 16, 16, 18, 11])

In [104]:
ind=np.argsort(num,kind='mergsort')
ind

array([4, 2, 3, 5, 0, 9, 1, 6, 7, 8])

In [106]:
num[ind]

array([ 5,  7,  8,  9, 11, 11, 16, 16, 16, 18])

In [108]:
np.sort(num)

array([ 5,  7,  8,  9, 11, 11, 16, 16, 16, 18])

In [112]:
#copy
num1=np.copy(num)
num1

array([11, 16,  7,  8,  5,  9, 16, 16, 18, 11])

In [122]:
#reshape
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape,arr.size)

[[1 2 3]
 [4 5 6]] (2, 3) 6


In [126]:
print(arr.reshape((3,2)))

[[1 2]
 [3 4]
 [5 6]]
